on:
    push:
        branches:
            - main
    pull_request:

name: CI

jobs:
    ci:
        strategy:
            matrix:
                toolchain: [stable]
                args: [--no-default-features, --all-features, --features auth]
                include:
                    - toolchain: nightly
                      args: --all-features
            fail-fast: false
        runs-on: ubuntu-latest
        name: Run CI on ${{ matrix.toolchain }} with args ${{ matrix.args }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.toolchain }}
                  override: true
            - name: cargo check
              uses: actions-rs/cargo@v1
              with:
                  command: check
                  args: ${{ matrix.args }}
            - name: Run tests
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: ${{ matrix.args }}

    clippy-rustfmt:
        runs-on: ubuntu-latest
        name: Run rustfmt and clippy
        needs: ci
        steps:
            - uses: actions/checkout@v2
            - name: Setup toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  components: rustfmt, clippy
                  override: true
            - name: clippy
              uses: actions-rs/clippy-check@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  args: --all-features
            - name: rustfmt
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: -- --check
