on: [push, pull_request]
jobs:
    ci:
        strategy:
            matrix:
                toolchain: [stable, beta, nightly]
                args:
                    [
                        --no-default-features,
                        --features enterprise,
                        --features auth,
                    ]
            fail-fast: false
        runs-on: ubuntu-latest
        name: Run CI on ${{ matrix.toolchain }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.toolchain }}
                  override: true
            - name: cargo check
              uses: actions-rs/cargo@v1
              with:
                  command: check
                  args: ${{ matrix.args }}
            - name: clippy
              uses: actions-rs/clippy-check@v1
              continue-on-error: true
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  args: ${{ matrix.args }}
            - name: rustfmt
              uses: actions-rs/cargo@v1
              continue-on-error: true
              with:
                  command: fmt
                  args: -- --check
            - name: Run tests
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: ${{ matrix.args }}
